
# filesystem
source      : .
destination : ./_site
plugins     : ./_plugins
exclude     : [.git, Gemfile, Gemfile.lock, .gitignore]

permalink : "/news/:title"

auto   : false
lsi    : false
safe   : false
server : false


