
# filesystem
source      : .
destination : ./_site
exclude     : [.git, Gemfile, Gemfile.lock, .gitignore]
include     : [stylesheets]

# gitub compatibility
safe     : true
lsi      : false
pygments : true


# misc
auto   : false
server : false


