
# filesystem
source      : .
destination : ./_site
plugins     : ./_plugins
exclude     : [.git, Gemfile, Gemfile.lock, .gitignore]

url       : "http://h2s.github.com/ppl"
permalink : "/news/:title"

auto   : false
lsi    : false
safe   : false
server : false

version: 2

