
# filesystem
source      : .
destination : ./_site
plugins     : ./_plugins
exclude     : [.git, Gemfile, Gemfile.lock, .gitignore]
include     : [stylesheets]

# misc
auto     : false
safe     : false
server   : false

