name: Build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.16.x"
      - name: Install dependencies
        run: bundle install
      - name: rspec
        run: bundle exec rake spec
      #- name: cucumber
      #  run: bundle exec rake features
      - uses: dawidd6/action-publish-gem@v1
        continue-on-error: true
        if: ${{ github.ref == 'refs/heads/trunk' }}
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}

